### PR TITLE
Migrate the underlying sass compiler to Embedded Sass instead of SassC

### PR DESCRIPTION
**Pull request by jhubert**
SassC has been deprecated and replaced with Dart Sass, which is implemented for ruby through the sass-embedded gem.

This change simply swaps embedded-sass in place of SassC.

This should allow https://github.com/bootstrap-email/bootstrap-email/pull/165 to pass and be merged in. 

I added an additional commit:

ad1b61bdda4fe0f78b80fd760400e7b779b4652c - The previous test HTML output had the word transparent wrapped in double quotes for reasons I'm not clear on. I don't think that's standard HTML / CSS syntax. When I migrated to Embedded Sass that went away, so I checked in the change.

I'm not sure what practices you follow, but I would recommend a version bump to 1.5 for this if you decide to merge and release it.

### CODE REVIEW

**Comment by jhubert** [comment]
There are some subtle changes to the text output files when this runs because they are currently written from version 1.4.0 and the current version of the gem is 1.4.1. I don't believe this has anything to do with my changes.

**Comment by jhubert** [comment]
This is now running in production on one of my services. So far, so good. 😄

**Comment by stuyam** [comment]
@jhubert thank you for your contribution, merging this and will work on a deploy on a new version 👍

**Comment by joarobles** [comment]
Hi there! This change causes blocking execution problems when running in the Docker image `ruby:3.1.2` as in #263

**Comment by nirvdrum** [comment]
@joarobles Were you able to find a reproduction? I'm seeing a blocking issue in CI since the _sass-embedded_ migration, but I'm struggling to reproduce the issue locally to debug it.

**Pull request merged**
